name: Production

on:
  release:
    types: [published]

jobs:
  create_environment_files:
    name: Create environment files
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Create - AWS credentials file
        run: |
          echo "[default]" > credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}" >> credentials

      - name: Create application.properties file
        run: |
          echo "spring.application.name=${{ secrets.SPRING_APPLICATION_NAME }}" > application.properties
          echo "server.port=${{ secrets.SERVER_PORT }}" >> application.properties

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: environment-files
          path: |
            credentials
            application.properties

  build_and_push:
    name: Build and push
    needs: create_environment_files
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: environment-files
          path: environmentsTempFiles

      - name: List directory to check
        run: ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'

      - name: Move AWS credentials file
        run: mv ${PWD}/environmentsTempFiles/credentials ${PWD}/credentials

      - name: Move application.properties file
        run: mkdir ${PWD}/src/main/resources && mv ${PWD}/environmentsTempFiles/application.properties ${PWD}/src/main/resources/application.properties

      - name: Get tag number
        run: echo "Tag number -> prod-${{ github.event.release.tag_name }}"

      - name: Build And Push To Dockerhub
        uses: Juanes2499/github-actions-templates/build-and-push-dockerhub.yml
        with:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_FILE_PATH: ./deployment/Dockerfile.build
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
          TAG: prod-${{ github.event.release.tag_name }}
